language: python

python: 
  - "3.7"

before_install:
  - export API_KEY=DUMMY
  - export DATABASE_URL=DUMMY

install: pip install -r requirements.txt

script: python -c 'from app import *'

branches:
  only:
    - master
